---
# To create the correct file use the following command:
#  oc create secret generic assisted-deployment-pull-secret -n assisted-installer \
#  --from-file=.dockerconfigjson=pull-secret.json --type=kubernetes.io/dockerconfigjson
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: pull-secret
  namespace: assisted-installer
stringData:
  .dockerconfigjson: '{"auths":{"lab-registry.ocpmgmt.lab.diktio.net":{"auth":"bnNhdHNpYTpSZWRoYXQwMQ==","email":"nsatsia@redhat.com"}}}'
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: assisted-deployment-pull-secret
  namespace: assisted-installer
stringData:
  .dockerconfigjson: '{"auths":{"lab-registry.ocpmgmt.lab.diktio.net":{"auth":"bnNhdHNpYTpSZWRoYXQwMQ==","email":"nsatsia@redhat.com"}}}'
