---
# https://github.com/openshift/assisted-service/blob/master/docs/operator.md#specifying-environmental-variables-via-configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  namespace: assisted-installer
data:
  LOG_LEVEL: "debug"
---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  namespace: assisted-installer
  annotations:
    # ConfigMap for Env variables (dev only)
    unsupported.agent-install.openshift.io/assisted-service-configmap: 'assisted-service-config'
spec:
  databaseStorage:
    # storageClassName: lso-blockclass
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
  filesystemStorage:
    # storageClassName: lso-filesystemclass
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
  osImages:
    - openshiftVersion: "4.6"
      version: "46.82.202012051820-0"
    #  url: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso"
    #  rootFSUrl: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-live-rootfs.x86_64.img"
      url: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso"
      rootFSUrl: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-live-rootfs.x86_64.img"
    - openshiftVersion: "4.7"
      version: "47.83.202105220305-0"
    #  url: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.7/4.7.13/rhcos-live.x86_64.iso"
    #  rootFSUrl: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.7/4.7.13/rhcos-live-rootfs.x86_64.img"
      url: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.7/4.7.13/rhcos-live.x86_64.iso"
      rootFSUrl: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.7/4.7.13/rhcos-live-rootfs.x86_64.img"
    - openshiftVersion: "4.8"
      version: "48.84.202107202156-0"
    #  url: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-live.x86_64.iso"
    #  rootFSUrl: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-live-rootfs.x86_64.img"
      url: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-live.x86_64.iso"
      rootFSUrl: "http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-live-rootfs.x86_64.img"
