---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-hook-presync-csv.yaml
  - 05-agentserviceconfig.yaml
  - 05-assisted-pull-secret.yaml
  - 06-bmc-hypervisor4-sushy.yaml